---
- name: create ipa server
  become: true
  hosts: 
    - ipa
  roles:
    - ipa

- name: join ipa server
  hosts:
    - ipa_clients
  roles:
    - ipa_client
  become: true

- name: deploy cluster
  become: true
  hosts:
    - nodes
    - masters
  roles: 
    - kubeadm

- name: init master
  hosts:
    - "{{ groups['masters'][0] }}"
  roles:
    - master
  become: yes

- name: join nodes
  become: true
  hosts:
    - nodes
    - masters
  roles:
    - node
- name: jenkins
  become: true
  hosts:
    - jenkins
  roles:
    - jenkins
