---
- name: create ipa server
  become: true
  hosts:
    - ipa_servers
  roles:
    - ipa

- name: join ipa server
  hosts:
    - ipa_clients
  become: true
  tasks:
  - name: deploy ipa client role
    include_role:
      name: ipa_client
    when: deploy_ipa

- name: deploy cluster
  become: true
  hosts:
    - nodes
    - masters
  roles:
    - kubeadm

- name: init master
  hosts:
    - "{{ groups['masters'][0] }}"
  roles:
    - master
  become: yes

- name: join nodes
  become: true
  hosts:
    - nodes
    - masters
  roles:
    - node

- name: jenkins
  become: true
  hosts:
    - jenkins_servers
  roles:
    - jenkins
