---
# tasks file for node
- name: kubeadm join
  command: "{{ hostvars[groups['masters'][0]].join_command }}"
  args:
    creates:  /etc/kubernetes/pki/ca.crt
- name: add Extra args dropin
  copy:
    content: |
      [Service]
      Environment=KUBELET_EXTRA_ARGS=--node-ip={{ ansible_eth1.ipv4.address }}
    dest: /etc/systemd/system/kubelet.service.d/20-extra-args.conf
  register: kubelet_extra

- name: reload systemd
  command: systemctl daemon-reload
  when: kubelet_extra.changed

- name: restart kubelet
  systemd:
    name: kubelet
    state: restarted
  when: kubelet_extra.changed

